### ISSUE TITLE
How to interpret figure result-num.png in the hyp folder

### ISSUE THREAD

**Issue by LeZhengThu** [pswpswpsw/SKDMD#1]
Hi Dr. Pan @pswpswpsw ,
        I used your code and data sample to create the result-num.png to select sigma and r. However, from the figure, it's hard to tell why you choose sigma=3 and r=180. Can you give me some hints on how to interpret the figure? Thanks. 
![result-num](https://user-images.githubusercontent.com/18341929/126526012-f6122416-b4ba-406c-93cb-e59a7ac2e256.png)

**Comment by pswpswpsw** [comment]
Hi Le, @LeZhengThu 

It is a good question. Choosing rank = 180 and sigma = 3 is just one of a range of choices. 

Given the range in the figure, the selection is not very sensitive to sigma but rank can make some difference. It is good because it means **KDMD for this problem** is not very sensitive to the hyperparameter selection. However, some other problem might be.

For your question, you can choose 
- sigma from 2 to 6
- rank between 180 and 190. 

You can also increase the rank further but there is a trade off between accuracy, robustness and interpretability.

**Comment by LeZhengThu** [comment]
Dear Shaowu, @pswpswpsw 
        Thanks for the reply. If I understand you correctly, I should choose sigma=6 and rank=90 from the figure below. Since the number goes up monotonically, do I need to try some larger rank? 

![result-num](https://user-images.githubusercontent.com/18341929/126574376-994753c9-af8a-469a-997f-53cb507ae0a6.png)

**Comment by pswpswpsw** [comment]
@LeZhengThu This plot means your data looks nice! I guess you tried a simple case to verify this algorithm. 

No, you should not choose sigma = 6 rank = 90. Look at the label of Y-axis, it is the number of eigenfunctions below the error threshold. So, you want to **maximize** this value. Therefore, I will choose sigma around 2 and rank = 90. 

Choosing how many rank to keep depending on the your data, in your case, you can try to increase the rank above 90. But given your plot, I think you can try rank = 90 and run the algorithm just to give a try.

**Comment by LeZhengThu** [comment]
@pswpswpsw  Yes, it's a very simple system. I misunderstood the x axis of the plot. Now I see your point. I'll continue to play with your codes. Thank you very much.
