### ISSUE TITLE
convergence warning when performing multi-task learning mode selection

### ISSUE THREAD

**Issue by LeZhengThu** [pswpswpsw/SKDMD#2]
Dear Dr. Pan  @pswpswpsw ,
         When I was trying out the multi-task learning mode selection with my own data, sklearn raised the convergence warning. It said you might want to increase the number of iterations. But my iteration is already 1e5 and it was really a very simple system. My data was generated using a 2-dimensional ODE, which was very similar to the example in 4.1. The different part is that I use feature tractories as training data. I randomly selected N initial point in the space and used RK45 to integrate along time, containing M+1 time steps. 1 to M data points were saved as X, and 2 to M+1 data points were saved as Xnext. So the number of rows of both X and Xnext is N*M, and the number of column is 2. So in my data generation code, X and Xnext were previously stored, unlike code line 70-71 in the cv_kdmd_hyp.py file. I don't know if that caused the convergence warning.

**Comment by pswpswpsw** [comment]
@LeZhengThu Just ignore the convergence warning. That is mostly because of the imperfect coordinate descent from Sklearn. But for all of my problems, even if you have convergence warning, it works well given O(100-1000) iterations. Future development can be focused on having a much better algorithm for this multi-task learning step. 

Currently the code does not support multiple (long) trajectories for the *validation* step. It can be done by just call that function several times indeed. But for your problem, it seems that if you convert these trajectories into data pairs, then there is no problem for training. 

As for now, I suggest you just run 1 initial point (1 trajectory) with M+1 sampled data, and go through all of the steps including visualization to see the prediction result.

**Comment by LeZhengThu** [comment]
@pswpswpsw The prediction error was very very large when I saw the component curve. That’s why I went back to see where could the problem occur. The biggest difference is the configuration of the input data. Can you provide the code to reproduce the example Section 4.1? My case is the same 2-dimensional ODE.

**Comment by pswpswpsw** [comment]
@LeZhengThu just upload the toy 2d case, please check this [folder](https://github.com/pswpswpsw/SKDMD/tree/master/EXAMPLES/lusch)

**Comment by LeZhengThu** [comment]
@pswpswpsw Thank you, Dr. Pan.
