### ISSUE TITLE
recostruction error too large

### ISSUE THREAD

**Issue by LeZhengThu** [pswpswpsw/SKDMD#3]
Dear Dr. Pan @pswpswpsw ,
     My system has a simple nonlinear sine function. The hyperparam selection figure is as follows so that I choose rank=90 and sigma=4. But the reconstruction error plot looks very strange, and the error is also huge. My system is as follows:
```
def F_omib_2d_system(x):
    Pm = 1.2
    Pe = 1.6382
    Damp = 5
    w0 = np.math.pi*2*50
    TJ = 6

    F = np.zeros(x.shape)
    F[0] = x[1]
    F[1] = w0*(Pm - Pe*np.math.sin(x[0]) - Damp*x[1]/w0)/TJ

    return F

```
The phase space range is ```phase_space_range = [[-.2, 3], [-9.5, 9.5]]```
All the other codes are exactly the same as the lusch example. Can you help provide some hints on how I can improve to get better results?
![reConstr_decay_normalized_relative_eigen_error](https://user-images.githubusercontent.com/18341929/127758222-6799da0f-6812-4d46-bab9-888564eefe38.png)
![result-num](https://user-images.githubusercontent.com/18341929/127758226-757f4ff8-b403-420a-a384-6417b194ebfc.png)
![top_20_normalized_relative_eigen_error](https://user-images.githubusercontent.com/18341929/127758228-5ae2b836-f683-4d93-9ef9-b95fe3bd0720.png)

**Comment by pswpswpsw** [comment]
@LeZhengThu  your problem, for the range of your initial condition, shows sensitivity to the initial condition. 
It seems to be unphysical for some initial conditions (i.e., it blows up to infinity.). For all of my problems, things are not going to blowup (because they are physical and the damping is enough). For your system, there is an external forcing  `w0*Pm`. It keeps feeding energy to the system.

![myplot](https://user-images.githubusercontent.com/7966776/127760540-bdfbeb2f-fa5f-411a-9151-a8a954579a1f.png)

If you still want to play with this system, you can try some modifications in your validation plot. as you can see in your last plot, the error goes really high after a certain time. This is because the autonomous system deviates from the training regime and therefore causes the data-driven methods to fail. 

You should
1. choose a smaller validation time step (say 0.1), change `tspan_valid` to `np.linspace(0, 0.1, 100)`

Also, make sure you have changed the `1600_trainData.npz` with your own dataset.

**Comment by LeZhengThu** [comment]
@pswpswpsw  Yes, my purpose of finding the Koopman eigenfunctions is to extract the region of attraction that any initial point lying in the region will not blow up. I've created the train data with my own equation. But maybe I should limit all the initial point in the region of attraction, rather than the whole phase space.

**Comment by pswpswpsw** [comment]
@LeZhengThu I see your purpose now. So if you have multiple attractors in your problem (including the one goes to infinity), you need to carefully think about the problem for approximating Koopman operator. A good source to read is in my thesis: https://deepblue.lib.umich.edu/handle/2027.42/168008, go to **section 5.7**. 

In short, I think you need **non-linear decoder** instead of **linear reconstruction** for your system with multiple attractors. And I think if you want to do it globally, you need to use neural networks for example : https://epubs.siam.org/doi/abs/10.1137/19M1267246. 

Also, to find region of attraction, what theoretical people in Koopman operator field do is to:

- spawn a bunch of initial condition, run ODE solver to get each trajectory, make sure to integrate long enough
- then for each trajectory, compute some statistics on that trajectory, e.g., mean. 
- then assign each statistics of the trajectory to its initial condition, draw it like a contour in phase space.
- then you will see, the regime of attraction clearly

However, I think there are better ways to finding regime of attractions, rather than Koopman, if you know the system equation. For example, **given governing equation**, I will random initialize x in the phase space, and then use iterative methods solve `F(x)=0` or minimize `||F(x)||`. then locate these roots in the phase space.

**Comment by LeZhengThu** [comment]
@pswpswpsw  For my toy ODE, there are two attractors, a stable one and an unstable one, which is a saddle point. I'd like to draw the region of attraction for the stable one. Alexandre Mauroy published some work on how to link the region of attraction and Lyapunov function with the Koopman Eigenfunctions. 
The method you mentioned is the so-called generalized Laplace average method, right? I don't quite understand the third step, i.e. 'assign each statistics of the trajectory to its initial condition, draw it like a contour in phase space'.
For the toy system, I know its governing equation. But for practical systems, the equations and parameters are unknown. So I want to find some data-driven method, like Koopman Operator, to compute the region of attraction.
BTW, you mentioned I need non-linear decoder instead of linear reconstruction, did you mean that the SKDMD method is not a good way to approximate the eigenfunction of my system?

**Comment by pswpswpsw** [comment]
@LeZhengThu 
- it means you assign the statistics to the [x[0], x[1]] as a color. So it becomes [x[0], x[1], h], then you draw such colormap. 
- I don't know any magic model-free method to compute region of attraction without really going through all kinds of possibility. I would probably not using Koopman to ONLY get the domain of attraction. Because Koopman is doing a lot of jobs in linearizing the global phase space. If you are interested in model-based control, I think Koopman can do much better job.
- SKDMD is not designed for approximating systems with multiple eigenfunctions unless the system is so simple, e.g., duffiing oscillator with two stable attractors. 
- But I think you can start to use neural network to approximate your system. Start with a latent space of 2 dimension, then slowly increasing the dimension until you find the fitting is good. Then go through each eigenfunction, there should be one corresponding to domain of attraction. I had such results for simple duffing oscillator (in my other paper https://epubs.siam.org/doi/abs/10.1137/19M1267246.)

**Comment by LeZhengThu** [comment]
@pswpswpsw  That sounds cool. I'll turn to the other paper.
